### ISSUE TITLE
Run lock API quickstart with js sdk;

### ISSUE THREAD

**Issue by LZHK1ng** [mosn/layotto#692]
I want to try it.

**Comment by seeflood** [comment]
@LZHK1ng Ok. Thanks!

**Comment by LZHK1ng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by LZHK1ng** [comment]
![微信图片_20220704221528](https://user-images.githubusercontent.com/68213475/177172577-bc8b7b1f-8052-49e8-9ab3-5770b2379de8.png)
I have a problem when I compiled this file.
Can you help me see plz. @seeflood

**Comment by seeflood** [comment]
@LZHK1ng Sure. Could you list the commands to reproduce this error ?

**Comment by LZHK1ng** [comment]
ok!
# step 1. Set up the environment

docker run -itd --name redis-test -p 6380:6379 redis

# Running etcd under Docker

docker run -itd -p 2379:2379 --name etcd quay.io/coreos/etcd /usr/local/bin/etcd -advertise-client-urls http://0.0.0.0:2379 -listen-client-urls http://0.0.0.0:2379

cd docker/layotto-redis
# Start redis and layotto with docker-compose
docker-compose up -d

# finally
git clone https://github.com/layotto/js-sdk.git
cd js-sdk/demo
npm install
npm run test:all

And I think  it is has nothing to do with Docker.

**Comment by seeflood** [comment]
@LZHK1ng I can run the demos but failed because of other errors:
![image](https://user-images.githubusercontent.com/26001097/177303356-9a6a08aa-a254-4496-91c2-7dfe52f484b7.png)

You can search your error messages and try to solve it by removing the entire`node_modules` folder and re-installing it:
https://stackoverflow.com/questions/9023672/how-do-i-resolve-cannot-find-module-error-using-node-js

**Comment by seeflood** [comment]
@LZHK1ng Sorry for the delay!
Since the js pr https://github.com/layotto/js-sdk/pull/4 has been merged, could u improve the documentation now?
![image](https://user-images.githubusercontent.com/26001097/194975784-299252cd-50a8-402c-934b-30e6cced79c3.png)

https://mosn.io/layotto/#/zh/start/lock/start
https://mosn.io/layotto/#/en/start/lock/start
