### ISSUE TITLE
Make configuration API compatible with document model. 配置API适配document模型

### ISSUE THREAD

**Issue by zhenjunMa** [mosn/layotto#7]
**What would you like to be added**:

**Why is this needed**:

**Comment by tianjipeng** [comment]
@seeflood Can I help with anything?

**Comment by seeflood** [comment]
> @seeflood Can I help with anything?

Wow,thanks for your support!
This issue is pending, because the new version of configuration API is under discussion.
Besides this,layotto has many things to do:
- add integration test;
- add document on how to use layotto(currently we only have some quickstart demo,but that's not enough);
......

And I'm preparing for new community tasks this week:
- add node sdk
- add python sdk
- add c/c++ sdk
- add .net sdk
- add more sdk api into java sdk
- add more unit test whereever you like to make layotto's unit test coverage higher(currently it's only 45%)
- use other components to implement distributed lock API (mongo,cassandra,consul,etc.)

**Comment by tianjipeng** [comment]
Let me add integration test first. Is there anything I should pay attention to?

**Comment by seeflood** [comment]
> Let me add integration test first. Is there anything I should pay attention to?

Cool,I will assign u
因为在高铁上信号不好，晚点告诉你细节

**Comment by seeflood** [comment]
@tianjipeng 
抱歉等这么久才回，因为我在研究该咋加集成测试，目前看来有点麻烦，得在github action的workflow中部署多个docker镜像，包含我们依赖的所有组件（redis,etcd,zookeeper等）然后再运行各种demo、判断有没有报错。

我怕你不熟悉项目，搞这个会很难上手，要不我来搞这个，你看下有没有其他感兴趣的任务？

我在 #108  又加了一些任务，包括：
- 测试类：为runtime/runtime.go和grpc/api.go添加单元测试。这两个文件是layotto的核心引擎代码，各自负责组件生命周期管理（启动、注册、初始化）和grpc请求处理，完成此任务可以很好的了解Layotto架构
- 文档类：为各类API新增接口文档、新增sdk使用文档（我最近肝了很多文档感觉还是不够……）

**Comment by tianjipeng** [comment]
我先来搞一下这两个文件的单测，后面再来看看怎么完善文档

**Comment by seeflood** [comment]
> 我先来搞一下这两个文件的单测，后面再来看看怎么完善文档

感激！！比心ღ( ´･ᴗ･` )
