### ISSUE TITLE
Proposal: support package management & pluggable component

### ISSUE THREAD

**Issue by helbing** [mosn/layotto#808]
# Background

The following problems I met when I used Layotto.

- Strong dependency on APIs. Users must commit new APIs to Layotto when existing APIs can't implement their requirements. It may wait for a long time until Layotto merges it. This is unacceptable for users who need to work to deadlines.
- Complex dependencies. such as the problem of MOSN. It makes Layotto still use go1.14. #792 

# Design

## Package management

![image](https://user-images.githubusercontent.com/7275620/193851308-db93d733-da6f-4889-937b-e823364baa19.png)

- Reduce dependencies on APIs. The community can maintain standard APIs.
- Fix complex dependencies in Layotto.
- Loading components on demand through package management.
- Generate multi-language clients via APIs.

### go plugin component

Pros:

- Low overhead, near built-in performance.

Cons:

- Only works on Linux、FreeBSD and macOS, not support Windows.
- Many problems make it difficult to use for development. [Go 原生插件使用问题全解析](https://www.sofastack.tech/blog/go-native-plug-in-use-problem-full-analysis/)
- Only develop in Go.

### gRPC component(Unix Domain Socket)

![image](https://user-images.githubusercontent.com/7275620/193973045-02df61f0-e266-4bb9-806c-54e79afee069.png)

Pros:

- Develop in multi-language that supports gRPC.
- Good isolation. Problems with components don't have a fatal impact on Layotto.

Cons:

- Latency is higher than the go plugin.

### Other

TODO

# Plan

These proposals will have a significant impact, so we must clarify many questions and write some examples to verify.

- [TODO]

# References

- dapr/dapr#4925
- [go-plugin](https://github.com/hashicorp/go-plugin)

**Comment by seeflood** [comment]
Thanks for your great proposal !

>Strong dependency on APIs. Users must commit new APIs to Layotto when existing APIs can't implement their requirements. It may wait for a long time until Layotto merges it. This is unacceptable for users who need to work to deadlines.

We have an ["API plugin" mechanism](https://mosn.io/layotto/#/zh/start/api_plugin/helloworld) to let users extend Layotto. Users can import Layotto (instead of forking Layotto) in their `main.go` and register their own API. They don't have to commit the API to Layotto community with this technique. Does this feature solve your problem?

- Complex dependencies
Yes it's indeed a problem, because we have to use go 1.14 for all the packages, which limits our development. I'm reading your reference links 

- Loading components on demand through package management
I'm curious about it. Could u explain more in detail?
