### ISSUE TITLE
Develop RabbitMQ component for Delay Queue API; 为 Delay Queue API 开发 RabbitMQ 组件

### ISSUE THREAD

**Issue by shawnh2** [mosn/layotto#852]
**What would you like to be added**:

Develop a new component for **Delay Queue** API.

- RabbitMQ

**Why is this needed**: refer to issue #840

We need more components to make this API useful

**Comment by ShawnHXH** [comment]
Do I have to register the component in `cmd/layotto/main.go`, `cmd/layotto_multiple_api` and `cmd/layotto_without_xds` in `NewRuntimeGrpcServer`? Cause [delay_queue/azure/servicebus](https://github.com/mosn/layotto/pull/807) does not.

**Comment by seeflood** [comment]
> Do I have to register the component in `cmd/layotto/main.go`, `cmd/layotto_multiple_api` and `cmd/layotto_without_xds` in `NewRuntimeGrpcServer`? Cause [delay_queue/azure/servicebus](https://github.com/mosn/layotto/pull/807) does not.

You don't have to

**Comment by ShawnHXH** [comment]
It seems that the module `github.com/dapr/components-contrib v1.5.2` need change to a new version, becasue it doesn't support message TTL in `pubsub/rabbitmq` util [this PR](https://github.com/dapr/components-contrib/pull/2093).

**Comment by seeflood** [comment]
@ShawnHXH Which version do you want to upgrade to?
It's OK to upgrade the module, but please make sure there are no incompatibilities

**Comment by ShawnHXH** [comment]
Oops, the current newest version of `github.com/dapr/components-contrib` (v1.9.0) does not support that features yet, so I have to wait for the next release.

**Comment by ShawnHXH** [comment]
> @ShawnHXH Which version do you want to upgrade to? It's OK to upgrade the module, but please make sure there are no incompatibilities

The latest version of `github.com/dapr/components-contrib` (v1.9.6) does not support this features yet, so I have to wait the next release.

**Comment by seeflood** [comment]
@ShawnHXH OK

**Comment by ShawnHXH** [comment]
@seeflood Hi, the latest version of `github.com/dapr/components-contrib` (v1.10.1) has been released, now it supports delay queue for rabbitmq.

But a conflict has been found, in v1.10.1, the `state/cloudstate` has been canceled, should we remove this from factory?

https://github.com/mosn/layotto/blob/7abad2f224736a38c1fed7364f3a3ebde7dfd055/cmd/layotto/main.go#L386-L388

Or have another purposes of using it?

**Comment by seeflood** [comment]
@ShawnHXH Ok, we can remove it. As far as I know, there's no user using this component now

**Comment by ShawnHXH** [comment]
@seeflood hi, before I implement this component, I upgrade dapr/components-contrib from v1.5.2 to v1.10.1.

It solved some conflicts and incompatibilities.

**Comment by ShawnHXH** [comment]
@seeflood Hello again, there're few things we need to talk about before this upgradation.

---

First,
layotto need to upgrade Go version from v1.18 => v1.19 (let's say v1.19.1) nor this upgradation won't pass the CI; because:

- dapr/components-contrib v1.10.1 require minimal Go version of >1.19, nor some dependencies may fail during go-build
- that means all the go versions in .github/workflow also need to change

I wanna make sure that if it is okay for layotto to do that?

---

Second,
When I'm testing with the CodeCov, something funny happend:
<img width="750" alt="image" src="https://user-images.githubusercontent.com/40317966/224552652-bc7d07d1-32a9-4b7a-b88f-185e33fa1ba4.png">
The CodeCov workflow is not using Go v.1.19, even though I've changed all the versions in workflow config. 
After I checked, this CodeCov runs directly using make command,
<img width="525" alt="image" src="https://user-images.githubusercontent.com/40317966/224552761-0cfc65e6-1f58-45d5-bf64-7bb88768fe1a.png">

So I was wondering what's version of Go in this process? And how to alter it? Can you gimme some hints?

---

Thanks!

**Comment by wenxuwan** [comment]
> @seeflood Hello again, there're few things we need to talk about before this upgradation.
> 
> First, layotto need to upgrade Go version from v1.18 => v1.19 (let's say v1.19.1) nor this upgradation won't pass the CI; because:
> 
> * dapr/components-contrib v1.10.1 require minimal Go version of >1.19, nor some dependencies may fail during go-build
> * that means all the go versions in .github/workflow also need to change
> 
> I wanna make sure that if it is okay for layotto to do that?
> 
> Second, When I'm testing with the CodeCov, something funny happend: <img alt="image" width="750" src="https://user-images.githubusercontent.com/40317966/224552652-bc7d07d1-32a9-4b7a-b88f-185e33fa1ba4.png"> The CodeCov workflow is not using Go v.1.19, even though I've changed all the versions in workflow config. After I checked, this CodeCov runs directly using make command, <img alt="image" width="525" src="https://user-images.githubusercontent.com/40317966/224552761-0cfc65e6-1f58-45d5-bf64-7bb88768fe1a.png">
> 
> So I was wondering what's version of Go in this process? And how to alter it? Can you gimme some hints?
> 
> Thanks!

Due to the user's internal version, layotto should not be able to directly upgrade to golang1.19 at present. You can submit a pr first, and then let's see together what features dapr relies on golang1.19.
